version: '3'
services:
  frontend:
    image: frontend-gestion-laboratoires-image
    ports:
      - "80:80"
  
  backend:
    image: backend-gestion-laboratoires-image
    ports:
      - "8080:8080"
    depends_on:
      - frontend
