apiVersion: apps/v1
kind: Deployment
metadata:
  name: utilisateur-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utilisateur-service
  template:
    metadata:
      labels:
        app: utilisateur-service
    spec:
      containers:
        - name: utilisateur-service
          image: musashi93/utilisateur-service:1.0  # Make sure this matches
          ports:
            - containerPort: 8080  # Your service port
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: utilisateur-service
spec:
  selector:
    app: utilisateur-service
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 8080 # Port on which the container is listening
      name: http
  type: ClusterIP
