pipeline {
    agent any

    environment {
        NODE_HOME = "${tool 'NodeJS'}" // Adjust 'NodeJS-20' to match your Jenkins NodeJS tool configuration name
        PATH = "${NODE_HOME}/bin:${env.PATH}" // Ensure Node.js is in the PATH
    }

    stages {
        stage('Checkout') {
            steps {
                dir('Frontend-GestionLaboratoires'){    
                    echo "Cloning the repository..."
                    checkout scm
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Frontend-GestionLaboratoires'){
                    echo "Installing dependencies..."
                    bat '''
                        node -v
                        npm install
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Frontend-GestionLaboratoires'){
                    echo "Running tests with Jest..."
                    bat 'npm run test -- --watch=false'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('Frontend-GestionLaboratoires'){
                    echo "Building the Angular application..."
                    bat 'npm run build -- --configuration=production'
                }
            }
        }

        stage('Archive Build') {
            steps {
                dir('Frontend-GestionLaboratoires'){
                    echo "Archiving build artifacts..."
                    archiveArtifacts artifacts: 'dist/**', fingerprint: true
                    
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'farehAbdallah' // Only deploy from the main branch
            }
            steps {
                dir('Frontend-GestionLaboratoires'){
                    echo "Deploying the Angular application..."
                    // Replace with your actual deployment steps
                    bat 'echo "Deployment step here"'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline completed."
        }
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
