pipeline {
    agent any
    tools {
        maven "Maven"
    }
    stages {
        stage('Checkout') {
            steps {
                // Clone the full repository from GitHub
                git url: 'https://github.com/farehAbdallah/GestionDesLaboratoires.git', branch: 'Ahmed'
            }
        }

        stage('Build and Test utilisateur Service') {
            steps {
                dir('Backend-GestionLaboratoires/UtilisateurService') {
                    // Run Maven build and tests
                    bat 'mvn clean install -DskipTests=false'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Backend-GestionLaboratoires/UtilisateurService') {
                    // Build the Docker image with a specific tag
                    bat 'docker build -t musashi93/utilisateur-service:latest .'
                }
            }
        }


    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
