pipeline {
    agent any

    environment {
        MAVEN_HOME = tool name: 'Maven'  // Assurez-vous que le nom correspond au Maven configuré dans Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone le dépôt complet depuis GitHub
                git url: 'https://github.com/farehAbdallah/GestionDesLaboratoires.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                // Exécute la commande Maven clean install uniquement pour UtilisateurService
                bat "${MAVEN_HOME}\\bin\\mvn clean install"
            }
        }

        stage('Test') {
            steps {
                // Exécute les tests pour UtilisateurService
                bat "${MAVEN_HOME}\\bin\\mvn test"
            }
            post {
                always {
                    // Publie les rapports de tests générés pour UtilisateurService
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                // Package l'application pour UtilisateurService
                bat "${MAVEN_HOME}\\bin\\mvn package"
            }
        }
    }

    post {
        success {
            echo 'Le pipeline pour UtilisateurService a été exécuté avec succès !'
        }
        failure {
            echo 'Le pipeline pour UtilisateurService a échoué.'
        }
    }
}
