apiVersion: v1
kind: Secret
metadata:
  name: mysql-gestionlaboratoire-secret
type: Opaque
data:
  username: cm9vdA==        # Base64-encoded value for "root"
  password:                 # Base64-encoded value for ""
