apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gestionlaboratoire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gestionlaboratoire
  template:
    metadata:
      labels:
        app: mysql-gestionlaboratoire
    spec:
      containers:
        - name: mysql-gestionlaboratoire
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-gestionlaboratoire-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "gestionlabolaboratoireDB"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-gestionlaboratoire
spec:
  selector:
    app: mysql-gestionlaboratoire
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
